name: FrendPlus
version: '${project.version}'
main: com.tanuch.FrendPlus
authors: [tanu_ch]
website: https://github.com/tanu-ch1111/FrendPlus
api-version: 1.8
commands:
  frend:
    description: フレンドコマンド
    usage: /frend <help|add|list|remove|accept|deny|reload>
permissions:
  frend.reload:
    description: メッセージの読み込みを行います
    default: op